LOG INTO HUGGING FACE
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: read).
Your token has been saved to /home/dan/.cache/huggingface/token
Login successful
load model
Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.77it/s]
tokenizer
load data
Data loaded
Traceback (most recent call last):
  File "/home/dan/mini_temporal/training/fine_tune_gemma_it.py", line 319, in <module>
    main()
  File "/home/dan/mini_temporal/training/fine_tune_gemma_it.py", line 228, in main
    train_data = other_preprocessing(train, tokenizer, args.model_context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/mini_temporal/training/fine_tune_gemma_it.py", line 135, in other_preprocessing
    dataset = Dataset.from_pandas(df2)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/danEnv/lib/python3.11/site-packages/datasets/arrow_dataset.py", line 870, in from_pandas
    table = InMemoryTable.from_pandas(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/danEnv/lib/python3.11/site-packages/datasets/table.py", line 720, in from_pandas
    return cls(pa.Table.from_pandas(*args, **kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 3869, in pyarrow.lib.Table.from_pandas
  File "/home/dan/miniconda3/envs/danEnv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 572, in dataframe_to_arrays
    convert_fields) = _get_columns_to_convert(df, schema, preserve_index,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/danEnv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 351, in _get_columns_to_convert
    columns = _resolve_columns_of_interest(df, schema, columns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dan/miniconda3/envs/danEnv/lib/python3.11/site-packages/pyarrow/pandas_compat.py", line 525, in _resolve_columns_of_interest
    columns = df.columns
              ^^^^^^^^^^
  File "/home/dan/miniconda3/envs/danEnv/lib/python3.11/site-packages/pandas/core/generic.py", line 6296, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Series' object has no attribute 'columns'